### ISSUE TITLE
请问有计划实现分享 API 吗？

### ISSUE THREAD

**Issue by kinhunt** [soliury/react-native-wechat-api#1]
```
而js 调用oc目前我还没有找到一个好的模式去用这个分享API, 难道每次传一个url path?
```

每次传一个url path，问题在哪里？

**Comment by osdio** [comment]
问题在于很多时候分享是直接传递一个img data，如果传递一个url，还读取url地址，然后在解析。。。。。

**Comment by osdio** [comment]
但是貌似只有这样一个方法，其实这个也比较好解决，你是需要这个功能么

**Comment by kinhunt** [comment]
@soliury 是的，如果缺少这个功能似乎就不够完整了。

另外一个提议，如果 js code 自己来负责下载，然后以传递 base64 给这个 module ，会不会相对合理？

update:
恩，这个提议好像不一定具有可行性，rn 通过 fetch 取回来的图片应该是 binary，怎么传递或转换成 UIImage 是个问题。

**Comment by kinhunt** [comment]
或者结合这个module？：
https://github.com/johanneslumpe/react-native-fs

**Comment by osdio** [comment]
对，初步想法是这样，我这两天比较忙，可能没时间搞，你很急需么？或者你可以提一个PR

**Comment by kinhunt** [comment]
@soliury 

```
对，初步想法是这样
```

哪样？你觉得传 image data 合适还是通过 fs 传 path？我也想 PR，可惜不会写 objc，有心无力 :)

ps, 并不急需 take ur time :)

**Comment by osdio** [comment]
就是传递url path，嗦嘎，我还以为你急需勒

**Comment by xiaoyann** [comment]
传url path有什么问题吗？我就是这样做的，因为我也不会OC，不知道有什么好办法。[react-native-wechat-ios](https://github.com/beefe/react-native-wechat-ios)

**Comment by osdio** [comment]
嗦嘎，又多一个轮子。。。哈哈

**Comment by xiaoyann** [comment]
哈哈，自己要用，所以就搞了，折腾折腾挺锻炼人的。

**Comment by osdio** [comment]
建议把安卓和ios的合成一个项目，

**Comment by xiaoyann** [comment]
嗯，好主意

**Comment by osdio** [comment]
没必要分成两个，完全是多此一举，那既然你在维护rn wechat，那我这个就可以退休了。。哈哈，我之前是拿来测试写rn native module的，我自己都嘿没有用过自己写得库

**Comment by xiaoyann** [comment]
嗯，多谢指点
